# Registry Adapter Environment
REGISTRY_URL={{REGISTRY_URL}}
CHAIN_RPC_URL={{CHAIN_RPC_URL}}
CHAIN_ID={{CHAIN_ID}}
PRIVATE_KEY={{PRIVATE_KEY}}
PORT=4100

# Contract Addresses
CARBON_CREDIT_CONTRACT={{CARBON_CREDIT_CONTRACT}}
EVIDENCE_ANCHOR_CONTRACT={{EVIDENCE_ANCHOR_CONTRACT}}

# Logging
LOG_LEVEL=info
NODE_ENV=development
