# Buyer Marketplace Environment
NEXT_PUBLIC_REGISTRY_API_URL={{REGISTRY_URL}}
NEXT_PUBLIC_ADAPTER_API_URL={{ADAPTER_URL}}
NEXT_PUBLIC_EXPLORER_BASE_URL={{EXPLORER_URL}}
NEXT_PUBLIC_BRAND_NAME=Carbon Market (Demo)
COOKIE_NAME=buyer_sess
COOKIE_SECURE=false
PORT=3004

# API Configuration
REGISTRY_URL={{REGISTRY_URL}}
ADAPTER_URL={{ADAPTER_URL}}
EXPLORER_URL={{EXPLORER_URL}}
BUYER_URL={{BUYER_URL}}

# Logging
LOG_LEVEL=info
NODE_ENV=development
