# Chain Environment
CHAIN_RPC_URL={{CHAIN_RPC_URL}}
CHAIN_ID={{CHAIN_ID}}
PRIVATE_KEY={{PRIVATE_KEY}}

# Contract Addresses (populated after deployment)
CARBON_CREDIT_CONTRACT={{CARBON_CREDIT_CONTRACT}}
EVIDENCE_ANCHOR_CONTRACT={{EVIDENCE_ANCHOR_CONTRACT}}
