# Carbon Explorer Environment
NEXT_PUBLIC_REGISTRY_URL={{REGISTRY_URL}}
NEXT_PUBLIC_ADAPTER_URL={{ADAPTER_URL}}
NEXT_PUBLIC_LOCKER_URL={{LOCKER_URL}}
PORT=3002

# API Configuration
REGISTRY_URL={{REGISTRY_URL}}
ADAPTER_URL={{ADAPTER_URL}}
LOCKER_URL={{LOCKER_URL}}

# Logging
LOG_LEVEL=info
NODE_ENV=development
