# Evidence Locker Environment
MINIO_ENDPOINT={{MINIO_ENDPOINT}}
MINIO_ACCESS_KEY={{MINIO_ACCESS_KEY}}
MINIO_SECRET_KEY={{MINIO_SECRET_KEY}}
MINIO_BUCKET={{MINIO_BUCKET}}
IPFS_URL={{IPFS_URL}}
PORT=4600

# Logging
LOG_LEVEL=info
NODE_ENV=development
